### ISSUE TITLE
Add my Fantastic Program to The kernel

### ISSUE THREAD

**Issue by Maxi1357** [Abb1x/emerald#1]
Do it n o w

**Comment by PhereloHD** [comment]
yes yes

Maxi <notifications@github.com> schrieb am So., 1. Nov. 2020, 22:41:

**Comment by Abb1x** [comment]
> Do it n o w
> 
> 

What's your program?

**Comment by Maxi1357** [comment]
![RemoveTheGifExtensionIdiot](https://user-images.githubusercontent.com/48174865/97900897-a39a3380-1d3b-11eb-82ed-d5a3a5b20b7a.gif)

**Comment by PhereloHD** [comment]
yes

Abb1x <notifications@github.com> schrieb am Mo., 2. Nov. 2020, 18:44:
