### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EmadDeve20** [Abb1x/emerald#15]
Why i can not run this?

![Screenshot from 2021-01-25 06-16-19](https://user-images.githubusercontent.com/60766355/105655437-498db200-5ed5-11eb-8f8e-6fa3949d9206.png)

what is my wrong?

**Comment by 9ahmed** [comment]
you need x86_64-elf-gcc

**Comment by 9ahmed** [comment]
if it doesnt work i suggest using xklap-x86_64-g++-build-nightly-git

**Comment by Abb1x** [comment]
> you need x86_64-elf-gcc

No

**Comment by Abb1x** [comment]
> Why i can not run this?
> 
> ![Screenshot from 2021-01-25 06-16-19](https://user-images.githubusercontent.com/60766355/105655437-498db200-5ed5-11eb-8f8e-6fa3949d9206.png)
> 
> what is my wrong?
> 

Reclone the new repo, you only need clang

**Comment by meisme-dev** [comment]
In the makefile, replace /home/abbix with /home/yourusername.

**Comment by Abb1x** [comment]
> In the makefile, replace /home/abbix with /home/yourusername.

Nope, this is not needed anymore

**Comment by Abb1x** [comment]
Just `rm - rf` the repo version you have right now, and reclone the repo

**Comment by meisme-dev** [comment]
Oh ok

**Comment by EmadDeve20** [comment]
> Just `rm - rf` the repo version you have right now, and reclone the repo

but this does not work and I again see an error!

```
CC=clang meson setup kernel/meson/ build/ && ninja -j4 -C build/
/bin/sh: 1: meson: not found
make: *** [Makefile:5: all] Error 127
```

**Comment by Abb1x** [comment]
> > Just `rm - rf` the repo version you have right now, and reclone the repo
> 
> but this does not work and I again see an error!
> 
> ```
> CC=clang meson setup kernel/meson/ build/ && ninja -j4 -C build/
> /bin/sh: 1: meson: not found
> make: *** [Makefile:5: all] Error 127
> ```
> 

Please look at the build guide

**Comment by EmadDeve20** [comment]
> > > Just `rm - rf` the repo version you have right now, and reclone the repo
> > 
> > 
> > but this does not work and I again see an error!
> > ```
> > CC=clang meson setup kernel/meson/ build/ && ninja -j4 -C build/
> > /bin/sh: 1: meson: not found
> > make: *** [Makefile:5: all] Error 127
> > ```
> 
> Please look at the build guide, it's in docs/

yea yea it's work it sorry i am stupid!
