### ISSUE TITLE
a new rewrite

### ISSUE THREAD

**Issue by 9ahmed** [Abb1x/emerald#16]
a new rewrite.. due to an issue in code

**Comment by 9ahmed** [comment]
![mydesktop](https://user-images.githubusercontent.com/65476194/105663202-910e4100-5ec9-11eb-9c57-c5b6a026dc58.png)

for reference

**Comment by 9ahmed** [comment]
![image](https://user-images.githubusercontent.com/65476194/105664723-44c50000-5ecd-11eb-82df-73bebda649fd.png)


old example of my clean java coding back in the day

**Comment by meisme-dev** [comment]
CAN YOU PLEASE STOP I GET NOTIFICATIONS FROM YOUR ISSUES AND THEY'RE COMPLETELY USELESS.
