### ISSUE TITLE
Can't build (echfs-utils not found)

### ISSUE THREAD

**Issue by j4cobgarby** [Abb1x/emerald#17]
I'm trying to build this, following the build instructions exactly, but I get the following error when I type `make run`:

```
[ LIMINE ] build/kernel.elf
0+0 records in
0+0 records out
0 bytes copied, 3.405e-05 s, 0.0 kB/s
make: echfs-utils: No such file or directory
make: *** [Makefile:21: build/disk.hdd] Error 127
```

**Comment by Abb1x** [comment]
My bad, I didn't add it in the build guide.

Please follow the install instructions [here](https://github.com/echfs/echfs) then retry building the OS

**Comment by meisme-dev** [comment]
i liek pie
