### ISSUE TITLE
Too few arguments to function `self->set_used' in bitmap.c

### ISSUE THREAD

**Issue by llamaking136** [Abb1x/emerald#27]
While attempting to build emerald, I got this error:
```
../libraries/libk/bitmap.c:106:37: error: too few arguments to function call, expected 3, have 2
    if (self->set_used(block, length) == 0)
        ~~~~~~~~~~~~~~              ^
1 error generated.
```
I checked the usage of `set_used` in bitmap.h and is as follows:
```
size_t (*set_used)(size_t, size_t, struct bitmap_struct *);
```
Where is the third argument, or an alternate version of `set_used`?

In the meantime, I'll look for a non-permanent solution.

**Comment by Abb1x** [comment]
Yes, it's possible, this part is still very WIP. So I recommend you to take a prebuilt image for now until I fix it.
Thanks for reporting an issue!
