### ISSUE TITLE
does not work on windows

### ISSUE THREAD

**Issue by m0ut0n** [Abb1x/emerald#4]

**Comment by Abb1x** [comment]
Please describe the problem

**Comment by m0ut0n** [comment]
my cpu is not suppported (ryzen 5 2400g)

**Comment by Abb1x** [comment]
> my cpu is not suppported (ryzen 5 2400g)
> 
What virtualization software?

**Comment by Abb1x** [comment]
Please follow the contribution template or this issue will be closed

**Comment by m0ut0n** [comment]
i dont care about you

**Comment by Abb1x** [comment]
issue closed
