### ISSUE TITLE
IMPORT DOCKERFILE RUB DUB DEFY ERROR SHARD

### ISSUE THREAD

**Issue by 9ahmed** [Abb1x/emerald#6]
please fix this.

**Comment by Abb1x** [comment]
please provide a description to your problem or it will be closed

**Comment by 9ahmed** [comment]
hey there, guy, i am trying to run makefile EmeraldOS with docker file. Please guide me

**Comment by Abb1x** [comment]
> hey there, guy, i am trying to run makefile EmeraldOS with docker file. Please guide me

what do you mean run makefile?

**Comment by 9ahmed** [comment]
> > hey there, guy, i am trying to run makefile EmeraldOS with docker file. Please guide me
> 
> what do you mean run makefile?

please, try to understand me
